### ISSUE TITLE
Cosas pa tu readme

### ISSUE THREAD

**Issue by Salmonidas** [JorgeGFS/Jorgegfs#1]
https://github-readme-stats.vercel.app/api?username=JorgeGFS&layout=compact&theme=dark&hide_border=true&count_private=true&show_icons=true&locale=es

https://github-readme-stats.vercel.app/api/top-langs/?username=JorgeGFS&layout=compact&theme=dark&hide_border=true&count_private=true&show_icons=true&langs_count=10&locale=es

**Comment by Salmonidas** [comment]
THEMES: https://github.com/anuraghazra/github-readme-stats

**Comment by DeJorgev** [comment]
Apañada
